<tr>
	<td><?php echo $this->last_name; ?></td>
	<td><?php echo $this->first_name; ?></td>
	<td><?php echo $this->unityid; ?></td>
	<td><?php echo $this->role; ?></td>
    <td><?php echo $this->semesterString ?></td>
	<td class='links'>
      <a href=<?php echo $this->url(array('module'=>'admin',
                                        'controller'=>'user',
                                        'action'=>'update',
                                        'unityid'=>$this->unityid));?>>Edit</a>
        | <a href=<?php echo $this->url(array('module'=>'admin',
                                          'controller'=>'user',
                                          'action'=>'delete',
                                          'unityid'=>$this->unityid));?>>Delete</a>
        | <a href=<?php echo $this->url(array('module'=>'admin',
                                          'controller'=>'user',
                                          'action'=>'view',
                                          'unityid'=>$this->unityid));?>>View</a>
	</td>
</tr>
