<div id="description">This calculator will determine a range of target heart rates based
on workout intensity using the Karvonen formula.</div>
<div id="form_wrapper">
	<div id="instructions">
		<h3>Instructions</h3>
		<ul>
			<li>&#187; Enter your current age</li>
			<li>&#187; Enter your resting heartrate</li>
			<li>&#187; Select your sex</li>
			<li>&#187; Click the calculate button</li>
		</ul>
	</div>
	<div id="form">
		<div id="calculator_form">
			<?php echo $this->form; ?>
		</div>
	</div>
</div>
