			<h3>Admin Menu</h3>
				<ul>
					<li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'dates', 'action' => 'modify'), null, true); ?>">&laquo; Modify Dates</a></li>
					<li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'list'), null, true); ?>">&laquo; List Users</a></li>
					<li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'add'), null, true); ?>">&laquo; Add User</a></li>
					<li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'grades', 'action' => 'index'), null, true); ?>">&laquo; List Grades</a></li>
          <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'workouts', 'action' => 'index'), null, true); ?>">&laquo; Add Workout</a></li>
				</ul>

