<!--			<h3>User Menu</h3>-->
				<ul>
					<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index'), null, true); ?>">&laquo; Home</a></li>
					<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'workout', 'action' => 'add'), null, true); ?>">&laquo; Add Workout</a></li>
					<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'workout', 'action' => 'view'), null, true); ?>">&laquo; View Workouts</a></li>
					<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'calculator', 'action' => 'add'), null, true); ?>">&laquo; HR Calculator</a></li>
					<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'update'), null, true); ?>">&laquo; Change Password</a></li>
					<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'login', 'action' => 'logout'), null, true); ?>">&laquo; Logout</a></li>
				</ul>

