<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php $this->headTitle()->setPostfix(' - Weekly Workout'); ?>
    <?php echo $this->headLink()
		->appendStylesheet($this->baseUrl() . '/css/layout.css')
		->appendStylesheet($this->baseUrl() . '/css/admin.css'); ?>

    <link rel="icon" type="image/jpg" href="/img/favicon.jpg"/>

</head>
<body class="<?php echo $this->bodyClass; ?>">
	<div id="wrapper">
		<div id="header">
			<center>
			<h1>Weekly Workout Log Application Admin</h1>
			</center>
		</div>
		<div id="menu">
			<div class="title">
				<span><?php echo $this->pageHeader; ?></span>
			</div>
		</div>
		<div id="body_wrapper">
			<div id="sidenav">
				<?php echo $this->partial("_userMenu.phtml"); ?>
				<?php echo $this->partial("_adminMenu.phtml"); ?>
			</div>
			<div id="main_content">
				<?php echo $this->layout()->content; ?>
			</div>
	</div>
</div>
</body>
</html>
